Styling the comments, adding a shebang and implementing the assembly code for thforce example

diff --git a/verilator_compare b/verilator_compare
--- a/verilator_compare
+++ b/verilator_compare
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+cd ..
+
 if [ ! -f "build.sbt" ]; then
     echo "Error: No 'build.sbt' detected"
     exit1
@@ -24,4 +26,14 @@ verilator --cc --exe --build -f filelist.f ../sim.cpp --top-module Core
 echo "--------- S I M U L A T I O N (Without Thforce) ---------"
 obj_dir/VCore
 
+cd ..
+
 cat examples/with_thforce.asm | sbt run
+
+if [ ! -f "generated/filelist.f" ]; then
+    echo "Error: No 'generated/filelist.f' found after build"
+    exit 1
+fi
+
+cd generated
+
